### ISSUE TITLE
Multi-Version item storage issue

### ISSUE THREAD

**Issue by GavvyDizzle** [dig/ender-vaults#12]
I've been running my server on 1.12.2 and players have many items stored in their vaults. After testing this plugin on 1.18.2, I noticed that the items had some issues. All lore is corrupted and it seems like all items with their material name changed between 1.12 and 1.18 are just deleted. 
![image](https://user-images.githubusercontent.com/57154434/176507035-6f345d16-6fc9-48ac-9f90-e3b44bfd81e1.png)

**Comment by dig** [comment]
Item storage was changed drastically between 1.12 and >1.13. The plugin uses Mojang's item format and I'm not sure if this is something I can look into fixing.

**Comment by GavvyDizzle** [comment]
That's unfortunate. I use Bukkit's item format in a few of my plugins and it works in both 1.12 and 1.18
