### ISSUE TITLE
Vault data has not been loaded yet, please wait...

### ISSUE THREAD

**Issue by marcelltorok** [dig/ender-vaults#4]
Yo I have a big problem, I buy your plugin and put to the plugins folder and restart my server.
And I see this message any time (Vault data has not been loaded yet, please wait...)

Server version: 1.16.5 (git-Paper-788)
Plugin version: 1.0.15, but I try with 1.0.13

Waiting for response...

**Comment by dig** [comment]
Out of interest, what did you do to solve this?
