### ISSUE TITLE
Support for 1.18

### ISSUE THREAD

**Issue by MoistMelonGaming** [dig/ender-vaults#6]
As of right now the plugin does not work for 1.18, Not actually trying to run a server in 1.18 as a production server but just wanted to see what was broken and what wasn't and this plugin came up in the list and I felt as if I should report it to you as I am sure you are already aware.

**Comment by Mirt-one** [comment]
We need update 1.18 plz.

**Comment by dig** [comment]
Hey, waiting on a library to support 1.18 before EnderVaults can :)

**Comment by dig** [comment]
Updated to 1.18!
