### ISSUE TITLE
1.18.2 Support

### ISSUE THREAD

**Issue by Loving11ish** [dig/ender-vaults#9]
Hello, me and my player base love this plugin!

Sadly as the plugin makes use of NMS, it no longer loads (obviously) on 1.18.2.

Please can you update this.

Many thanks

**Comment by UnluckyPandaa** [comment]
Would love for this to be updated as well!

**Comment by dig** [comment]
Updated to 1.18.2!

**Comment by Jcodeerd** [comment]
Thanks!!
